//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int oid { get; set; }
        public Nullable<int> oFKpro { get; set; }
        public Nullable<int> oFKuser { get; set; }
        public Nullable<int> oFKinvoice { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public Nullable<int> oqty { get; set; }
        public Nullable<double> obill { get; set; }
        public Nullable<int> ouprice { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
